:tip-caption: :bulb:
:warning-caption: 🤔
:sectnums:

= **Curso Algoritmos: Fundamentos**

== **Fundamentos**

Seja bem vindo ao primeiro capítulo do nosso curso, **fundamentos**! Nesse primeiro momento buscamos apresentar os conceitos chaves ligados a programação através da linguagem Python, dentre eles:

* Algoritmos
* Aspectos de linguagens de programação
* Variáveis & Tipos
* Estruturas de decisão
* Funções

Vamos lá?

=== **Algoritmos**
====
[quote, Oxford Lexico]
Trata-se de um processo ou conjunto de regras a serem seguidas em cálculos ou outras operações voltadas para solução de problemas[...]
====

Como a definção bem disse, algoritmos são 
basicamente uma série de instruções para resolução de problemas, não necessáriamente computacionais. Ou seja, se preparar para sair de casa de manhã, pode ser caracterizada como um algoritmo, veja:

. Levantar-se
. Tomar um banho
. Vestir-se
. Calçar o sapato
. Pegar itens essênciais(Chave, carteira etc)
. Comer
. Escovar os dentes
. Pegar a mochila
. Sair de casa

Que tal tentar identificar e tentar escrever alguns algoritmos que você usa diariamente?

[WARNING]
====
**Exercício Rápido** +
Identifique e escreva pelo menos 3 algoritmos!
====


=== Meu primeiro programa

O próximo exercício representa o nosso primeiro programa em Python!

.primeiro_programa.py
====
[source,python]
----
print("Olá python!") // <1>

// Resultado:
Olá python!

----
<1> **O método ``print`` nos permite imprimir algum valor no terminal. No caso imprimimos __Olá python! __**
====

[TIP]
Python também é possível quebrar a sentença em múltiplas linhas

.primeiro_programa.py
====
[source,python]
----
print("Olá python!")

print(
    "Olá Python!"
)
----
====
=== Variáveis e constantes
Para armazenar dados mutáveis como idade de uma pessoa, quilometragem de um carro, utilizamos variáveis, veja:

.variaveis_e_constantes.py
====
[source,python]
modelo = "Uno"
fabricado_por = "Fiat"
print("Modelo: " + modelo)
print("Marca: " + fabricado_por)
====

Já para armazenar dados imutáveis como tipo sanguíneo, polegada de uma tv utilizamos de constantes. 

.variaveis_e_constantes_2.js
====
[source,javascript]
----
var tipoSanguineo = "O+"

// Erro!
tipoSanguineo = "B+"
----
====

[IMPORTANT]
====
É imporante ressaltar que python não suporta constantes! Os desenvolvedores convencionaram que variáveis declaradas em caixa alta são "constantes" e não podem ser alteradas
====

.Pseudo constantes em Python
====
[source,python]
----
ANO = 2019
print(ANO)
ANO = 2020
print(ANO)
----
====

Outro recurso importante de toda linguagem de programação são comentários. Os comentários servem para apresentar em forma de texto uma informação adicional que talvez não esteja explicita no código. 

.Pseudo constantes em Python
====
[source,python]
----

# Python não possui constantes!
ANO = 2019
print(ANO)
ANO = 2020
print(ANO)
----
====

[CAUTION]
====
Evite criar comentários desnecessários!
====

=== Tipos básicos
No mundo real usamos letras para expressar nomes, palavras para expressar textos e numeros para representar valores e com isso em mente as linguagens de programação possuem alguns tipos básicos para podermos traduzir isso para linguagem de máquina, dentre eles: 

.Tipos básicos
|=== 
|*Tipo*    | *Uso*
| Char  | Letras 
| Strings  | Palavras
| Inteiros | Numeros
| Floats   | Decimais
| Boolean  | Expressões lógicas
|=== 

[IMPORTANT]
====
Python une letras e palavras em __Strings__ ao invés de separar em __Char__ e __String__
====
O exemplo abaixo apresenta um uso prático para esses tipos básicos veja: 

.Tipos básicos em Python
====
[source,python]
----    
titulo = "Pulp Fiction"
ano_lancamento = 1994
avalicao = 4.6
favorito = True

print(
    titulo,
    "foi lançado em",
    ano_lancamento,
    "e tem nota",
    avalicao
)
----
====

=== Tipagem fraca Vs Tipagem forte
A tipagem de uma linguagem de programação representa a capacidade de uma variável alterar seu tipo. Uma tipagem fraca também conhecida como dinâmica, permite que uma variável possa ser alterar de tipo sem apresentar erros. Já a tipagem forte ou estática representa o contrário, uma vez com seu tipo definido não pode ser mais alterado. 


Python por exemplo é uma linguagem com uma tipagem fraca, dessa forma permitindo que uma mesma variável possa ser atribuida com tipos diferentes, veja:

====
[source,python]
----
valor = 'Palavra'
print(valor)

valor = 3
print(valor)
----
====

Já se tentassemos traduzir o exemplo acima para a linguagem Dart, que possui uma tipagem forte, geraria um erro, veja: 

.Traduzindo para Dart
====
[source,dart]
----
main() {
  String valor = 'Palavra';
  print(valor);
  //  Erro!
  valor = 3;
  print(valor);

  dynamic outro = 'oito';
  print(outro);
  outro = 9.8;
  print(x);
}
----
====

[NOTE]
====
*dynamic* é uma palavra chave da linguagem Dart que habilita a tipagem dinâmica para a variável __outro__. Dessa forma podendo alterar seu tipo mesmo trantando de uma linguagem com tipagem forte.
====

=== Funções
// [REVIEW] poderia ter colocado aqui a definição de função
// [REVIEW] Faz sentido apresentar as funções internas depois de apresentar funções criadas pelo programador

Para definir funções em python utilizamos a palavra reservada ``def``

==== Criando suas próprias funções
.Primeira função em Python
====
[source, python]
----
def saudar():
    print("Olá! Sejam bem vindos!")

saudar()
----
====

==== Parâmetros
Parâmetros são valores a serem passados para a função, para fazer isso basta definir dentro do parêntesis da função declarada

.Funções com parâmetro
====
[source, python]
----
def saudar_pessoa(nome):
    print("Ola " + nome + "! Seja bem vindo!")

saudar_pessoa("João")
----
====

Podemos também passar mais de um parâmetro para uma função, separando-os por virgulas

.Funções com parâmetro
====
[source, python]
----
def somar(numero1, numero2): # <1>
    print(numero1 + numero2)

somar(1, 3) # <2>
----
. Para separar a declaração parâmetros utilizamos virgulas 
. O mesmo vale para a invocação
====


==== Funções que retornam
O retorno de uma função é basicamente o valor que a função gera quando é invocada. Podendo ser armazenado em uma variável ou diretamente utilizado para uma outra operação

.Funções com retorno
====
[source, python]
----
def dividir(divisor, dividendo):
    resultado = divisor / dividendo
    return resultado

dividir(10, 5) # <1>
print(dividir(10, 5)) # <2>

resultado_divisao = dividir(10, 5) # <3>
print(resultado_divisao)
----
. Somente chamar a função não irá aparecer nada
. Precisamos invocar a função dentro de um ``print`` para aparacer algum resultado
. Ou podemos armazenar em uma variável como em ``resultado_divisão```
====

==== Funções internas do Python
O python possui suas próprias funções interas, que estão presentes desde o início do curso, como a função ``print``
====
[source, python]
----
nome = "Bulano"
print(nome)
----
====

Além das formas apresentadas acima, existem outras formas de se invocar uma função, dentre elas

====
[source,python]
----
nome = "Bulano"
print(nome)

# Invocação com um parâmetro
len(nome)

# Invocação com dois parâmetros e através da notação ponto
nome.replace("B", "F") # <1>
print(nome)

nome = nome.replace("B", "F") # <2>
print(nome)
# Invocação através de um tipo literal
print("nome".upper()) # <3>
----
. Métodos internos do pyhton não alteram diretamente variáveis. Para alterá-las precisa reatribuir a variável(__ver bullet 2__)
. Reatribuição para alterar o valor da variável
. Tipos em python possuem seus próprios métodos, o que possibilita esse tipo de invocação
====


Existem também as funções que só podem ser acessadas uma vez que forem importadas

====
[source, python]
----
import datetime

hoje = datetime.datetime.now()
print (hoje.day, hoje.month, hoje.year)
print (hoje.hour, hoje.minute, hoje.second)
----
====

Podemos também importar apenas uma função da seguinte forma:

====
[source, python]
----
import datetime from datetime

hoje = datetime.now()
print (hoje.day, hoje.month, hoje.year)
print (hoje.hour, hoje.minute, hoje.second)
----
====


=== **Pratique**
. Escolha um objeto no seu arredor e tente identificar pelo menos 3 características
. Armazene as caracteristicas em variáveis identificando os tipos básicos corretos para cada característica(ex.: palavra = String)
. Declare uma função para imprimir as características do objeto escolhido

**Solução**
====
[source, python]
----
nome = "Violão"
modelo = "Lag"
qtd_cordas = 6


def descrever_violao(nome, modelo, qtd_cordas):
    print("O", nome, modelo, "possui", qtd_cordas, "cordas")

descrever_violao(nome, modelo, qtd_cordas)
----
====
