:tip-caption: :bulb:
:warning-caption: 🤔
:sectnums:

= **Curso Algoritmos: Fundamentos**

== **Fundamentos**

Seja bem vindo ao primeiro capítulo do nosso curso, **fundamentos**! Nesse primeiro momento buscamos apresentar os conceitos chaves ligados a programação através da linguagem Python, dentre eles:

* Algoritmos
* Aspectos de linguagens de programação
* Variáveis & Tipos
* Estruturas de decisão
* Funções

Vamos lá?

=== **Algoritmos**

[quote, Oxford Lexico]
Trata-se de um processo ou conjunto de regras a serem seguidas em cálculos ou outras operações voltadas para solução de problemas[...]
 
Como a definção bem disse, algoritmos são basicamente uma série de instruções para resolução de problemas, não necessáriamente computacionais. Ou seja, se preparar para sair de casa de manhã, pode ser caracterizada como um algoritmo, veja:

. Levantar-se
. Tomar um banho
. Vestir-se
. Calçar o sapato
. Pegar itens essênciais(Chave, carteira etc)
. Comer
. Escovar os dentes
. Pegar a mochila
. Sair de casa

Que tal tentar identificar e tentar escrever alguns algoritmos que você usa diariamente?


[WARNING]
Identifique e escreva pelo menos 3 algoritmos!

=== Meu primeiro programa
O próximo exercício representa o nosso primeiro programa em Python!

.primeiro_programa.py
[source,python]
----
print("Olá python!")
----
O método ``print``` nos permite imprimir algum valor no terminal. No caso imprimimos __Olá python! __

[TIP]
Python também é possível quebrar a sentênça em múltiplas linhas

.primeiro_programa.py
[source,python]
----
print("Olá python!")

print(
    "Olá Python!"
)
----

A seção <<teste-adoc>> fala sobre isso
 
